# Generated by Django 3.1 on 2020-08-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Blog_Category',
        ),
        migrations.CreateModel(
            name='Blog_article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_head', models.CharField(max_length=500, null=True)),
                ('article_summary', models.CharField(max_length=500, null=True)),
                ('article_text', models.CharField(max_length=5000, null=True)),
                ('article_img_url', models.TextField(null=True)),
                ('article_author', models.CharField(max_length=100)),
                ('article_author_profile', models.TextField(null=True)),
                ('article_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.blog_category')),
            ],
        ),
        migrations.AlterField(
            model_name='sets',
            name='set_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_category'),
        ),
    ]
